Version 0.5.0

diff --git a/bin/update-irnettools-databases b/bin/update-irnettools-databases
--- a/bin/update-irnettools-databases
+++ b/bin/update-irnettools-databases
@@ -35,8 +35,15 @@ else
     DB_PATH=`echo $DATABASES | sed -e "s|^~/|$HOME/|"`
 fi
 
-# Check if wget installed
-which wget >/dev/null 2>&1 || fail "wget not installed. Please install it."
+# Check if wget or curl installed
+if [ `which wget >/dev/null 2>&1; echo $?` -eq 0 ]; then
+    WGET=1
+else
+    WGET=0
+    if [ `which curl >/dev/null 2>&1; echo $?` -gt 0 ]; then
+        fail "Neither wget nor curl found. Please install one of them."
+    fi
+fi
 
 MM_DIR="${DB_PATH}/maxmind"
 MAXMIND_COUNTRY_FILE="${MM_DIR}/GeoLite2-Country.mmdb"
@@ -47,18 +54,36 @@ TMP_DIR=`mktemp -d`
 
 echo "Updating databases in $DB_PATH"
 echo "Updating Maxmind GeoLite2 Country database."
-wget -q -O "$TMP_DIR/country.tgz" "$MAXMIND_COUNTRY_URL"
+if [ -n "$WGET" ]; then
+    wget -q -O "$TMP_DIR/country.tgz" "$MAXMIND_COUNTRY_URL"
+else
+    curl -s -O "$TMP_DIR/country.tgz" "$MAXMIND_COUNTRY_URL"
+fi
 [ $? -gt 0 ] && fail "Downloading database failed"
 tar xzf "$TMP_DIR/country.tgz" -C "$TMP_DIR/" >/dev/null 2>&1
 [ $? -gt 0 ] && fail "Unpacking database failed"
-mv -f `find "$TMP_DIR/" -name GeoLite2-Country.mmdb` "$MAXMIND_COUNTRY_FILE"
+FILENAME=`find "$TMP_DIR/" -name GeoLite2-Country.mmdb`
+if [ -n "$FILENAME" ]; then
+    mv -f "$FILENAME" "$MAXMIND_COUNTRY_FILE"
+else
+    fail "Country database file not found in downloaded archive"
+fi
 
 echo "Updating Maxmind GeoLite2 ASN database."
-wget -q -O "$TMP_DIR/asn.tgz" "$MAXMIND_ASN_URL"
+if [ -n "$WGET" ]; then
+    wget -q -O "$TMP_DIR/asn.tgz" "$MAXMIND_ASN_URL"
+else
+    curl -s -O "$TMP_DIR/asn.tgz" "$MAXMIND_ASN_URL"
+fi
 [ $? -gt 0 ] && fail "Downloading database failed"
 tar xzf "$TMP_DIR/asn.tgz" -C "$TMP_DIR/" >/dev/null 2>&1
 [ $? -gt 0 ] && fail "Unpacking database failed"
-mv -f `find "$TMP_DIR/" -name GeoLite2-ASN.mmdb` "$MAXMIND_ASN_FILE"
+FILENAME=`find "$TMP_DIR/" -name GeoLite2-ASN.mmdb`
+if [ -n "$FILENAME" ]; then
+    mv -f "$FILENAME" "$MAXMIND_ASN_FILE"
+else
+    fail "ASN database file not found in downloaded archive"
+fi
 
 rm -rf "$TMP_DIR"
 #
